spring:
  application:
    name: notification-fonrt-server
  jackson:
    default-property-inclusion: NON_NULL
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:notification_schema;DB_CLOSE_ON_EXIT=FALSE;
    hikari:
      connection-timeout: 30000
      minimum-idle: 2
      maximum-pool-size: 20
      idle-timeout: 10000
      max-lifetime: 30000
  jpa:
    show-sql: false
    generate-ddl: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: false
        show_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100

---
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
---
springdoc:
  version: 1.0
  swagger-ui:
    path: /api-docs

---
logging:
  level:
    com.devpaik.nfs: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              basicBinder: TRACE
